f

diff --git a/.github/workflows/node.js.yml b/.github/workflows/node.js.yml
--- a/.github/workflows/node.js.yml
+++ b/.github/workflows/node.js.yml
@@ -6,18 +6,50 @@ on:
 
 jobs:
   build:
+
     runs-on: self-hosted
+
     strategy:
       matrix:
         node-version: [22.2.0]
 
     steps:
-      - uses: actions/checkout@v4
-      - name: Use Node.js ${{ matrix.node-version }}
-        uses: actions/setup-node@v3
-        with:
-          node-version: ${{ matrix.node-version }}
-          cache: 'npm'
-      - run: npm ci
-      - run: npm run build --if-present
-      - run: pm2 restart 8
+    - uses: actions/checkout@v4
+    - name: Use Node.js ${{ matrix.node-version }}
+      uses: actions/setup-node@v3
+      with:
+        node-version: ${{ matrix.node-version }}
+        cache: 'npm'
+    
+    # Install dependencies
+    - run: npm ci
+
+    # Build in a temporary directory
+    - name: Build in a temporary directory
+      run: |
+        mkdir temp_build
+        cp -R * temp_build/
+        cd temp_build
+        npm run build --if-present
+
+    # Test if the build was successful
+    - name: Check if build succeeded
+      run: |
+        if [ -d "temp_build" ]; then
+          echo "Build succeeded, proceeding with deployment..."
+        else
+          echo "Build failed, stopping process."
+          exit 1
+        fi
+
+    # If the build was successful, deploy the new version
+    - name: Deploy new build
+      if: success()
+      run: |
+        cp -R temp_build/* ./
+        rm -rf temp_build
+        pm2 restart 8
+
+    # Cleanup the temporary build directory
+    - name: Cleanup
+      run: rm -rf temp_build
